# Dockerfile for automation testing framework

# Usa una imagen base con Node.js
FROM node:14

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el package.json y package-lock.json para instalar las dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos del proyecto al directorio de trabajo
COPY . .

# Expone el puerto necesario para las pruebas (si es necesario)
EXPOSE 3000

# Comando para ejecutar las pruebas cuando se inicie el contenedor (sustituye con el comando específico de tus pruebas)
CMD ["npm", "test"]
